name: mlproject
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn=1.5.2
  - imbalanced-learn
  - matplotlib
  - seaborn
  - pip
  - pip:
      - xgboost
      - lightgbm
      - catboost
      - interpret
