name: mlproject
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn>=1.6
  - imbalanced-learn
  - matplotlib
  - seaborn
  - xgboost
  - lightgbm
  - catboost>=1.2.5
  - pip
  - pip:
      - interpret
