name: mlproject
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - imbalanced-learn
  - matplotlib
  - seaborn

  # Modelli extra (se il grader li supporta)
  - xgboost
  - lightgbm
  - catboost
  - interpret

