name: mlproject
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip

  - numpy<2
  - pandas
  - scipy

  - scikit-learn=1.5.2
  - imbalanced-learn

  - catboost>=1.2.5
  - xgboost
  - lightgbm

  - matplotlib
  - seaborn
